services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: rag-api:1.0
    restart: unless-stopped

    env_file:
      - .env

    environment:
      REDIS_URL: redis://rag-redis-vector:6379
      DATA_DIR: /app/data

    volumes:
      - type: bind
        source: D:/DOCKER/RAG-DOCS
        target: /app/data
        read_only: true

    cls

    networks:
      - rag-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile

    image: rag-api:1.0
    restart: unless-stopped

    command:
      - streamlit
      - run
      - src/app.py
      - --server.address=0.0.0.0
      - --server.port=8501

    env_file:
      - .env

    environment:
      REDIS_URL: redis://rag-redis-vector:6379
      API_URL: http://api:8000
      DATA_DIR: /app/data

    volumes:
      - type: bind
        source: D:/DOCKER/RAG-DOCS
        target: /app/data
        read_only: true

    ports:
      - "8501:8501"

    depends_on:
      - api

    networks:
      - rag-network

networks:
  rag-network:
    external: true
    name: rag-company-documents_rag-network